{ config, pkgs, lib, ... }:

{
  services.nginx.enable = true;

  # Ensure Nginx group can access the certificate keys generated by the ACME service
  users.users.nginx.extraGroups = [ "acme" ];

  services.nginx.virtualHosts."campgroundlabs.xyz" = {
    # Bind to our centralized Porkbun DNS-01 wildcard certificate
    useACMEHost = "campgroundlabs.xyz";
    forceSSL = true;
    
    # Catch any subdomain variants hitting your public IP
    serverAliases = [ "*.campgroundlabs.xyz" ];
    
    listen = [ 
      { addr = "0.0.0.0"; port = 443; ssl = true; }
      { addr = "0.0.0.0"; port = 8443; ssl = true; }
    ];

    locations = {
      # =========================================================================
      # 1. CORE INTERCEPTOR & DASHBOARD
      # =========================================================================
      "/" = {
        extraConfig = ''
          if ($server_port = 8443) {
            proxy_pass http://127.0.0.1:8080;
          }
          charset utf-8;
        '';
        root = pkgs.writeTextDir "index.html" ''
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Campground Home Lab</title>
            <style>
              body { font-family: sans-serif; background: #1a1a1a; color: #fff; text-align: center; padding-top: 50px; }
              .card { background: #2a2a2a; padding: 20px; border-radius: 8px; display: inline-block; margin: 15px; width: 200px; text-decoration: none; color: #00bcd4; border: 1px solid #444; text-align: left; }
              .card:hover { background: #333; border-color: #00bcd4; }
              .grid { display: flex; justify-content: center; flex-wrap: wrap; max-width: 900px; margin: 0 auto; }
            </style>
          </head>
          <body>
            <div style="max-width: 900px; margin: 0 auto; text-align: center; padding: 0 15px;">
              <h1 style="font-size: 2.5rem; margin-bottom: 5px;">⛺ Campground Server ⛺</h1>
              <p style="color: #aaa; margin-top: 0; margin-bottom: 40px;">Homelab Control Panel</p>
            </div>

            <div class="grid">
              <a href="https://audiobookshelf.campgroundlabs.xyz/" class="card">
                <h3>📚 Audiobookshelf</h3>
                <p>Stream your audiobooks and manage your media library.</p>
              </a>
              <a href="https://grafana.campgroundlabs.xyz/" class="card">
                <h3>📊 Grafana</h3>
                <p>View server metrics, dashboards, and alerts.</p>
              </a>
              <a href="https://vpn.campgroundlabs.xyz/" class="card">
                <h3>🔒 VPN Control</h3>
                <p>Manage WireGuard mesh nodes and device authorizations.</p>
              </a>
            </div>
          </body>
          </html>
        '';
      };

      # =========================================================================
      # 2. LEGACY PATH REDIRECTS TO SUBDOMAINS
      # =========================================================================
      "/audiobooks" = {
        return = "301 https://audiobookshelf.campgroundlabs.xyz/";
      };
      
      "/audiobookshelf" = {
        return = "301 https://audiobookshelf.campgroundlabs.xyz/";
      };

      "/audiobookshelf/" = {
        return = "301 https://audiobookshelf.campgroundlabs.xyz/";
      };

      "/vpn-admin" = {
        return = "301 https://vpn.campgroundlabs.xyz/";
      };

      "/vpn-admin/" = {
        return = "301 https://vpn.campgroundlabs.xyz/";
      };

      "/metrics" = {
        return = "301 https://grafana.campgroundlabs.xyz/";
      };

      "/metrics/" = {
        return = "301 https://grafana.campgroundlabs.xyz/";
      };
    };
  };

  services.nginx.virtualHosts."audiobookshelf.campgroundlabs.xyz" = {
    useACMEHost = "campgroundlabs.xyz";
    forceSSL = true;
    listen = [ { addr = "0.0.0.0"; port = 443; ssl = true; } ];
    locations."/" = {
      proxyPass = "http://127.0.0.1:13378/";
      proxyWebsockets = true;
      extraConfig = ''
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
      '';
    };
  };

  services.nginx.virtualHosts."grafana.campgroundlabs.xyz" = {
    useACMEHost = "campgroundlabs.xyz";
    forceSSL = true;
    listen = [ { addr = "0.0.0.0"; port = 443; ssl = true; } ];
    locations."/" = {
      proxyPass = "http://127.0.0.1:3000/";
      proxyWebsockets = true;
      extraConfig = ''
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
      '';
    };
  };

  services.nginx.virtualHosts."vpn.campgroundlabs.xyz" = {
    useACMEHost = "campgroundlabs.xyz";
    forceSSL = true;
    listen = [ { addr = "0.0.0.0"; port = 443; ssl = true; } ];
    locations = {
      # This catches all Tailscale client traffic and pipes it to Headscale.
      "~ ^/(apple|register|key|ts2019|machine|node|oidc|metrics|windows)" = {
        proxyPass = "http://127.0.0.1:8080$request_uri";
        proxyWebsockets = true;
        extraConfig = ''
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 86400;
        '';
      };
      "/" = {
        proxyPass = "http://127.0.0.1:3300/";
        proxyWebsockets = true;
        extraConfig = ''
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Prefix /;
          proxy_redirect off;
          proxy_buffering off;
          proxy_read_timeout 86400;
        '';
      };
      
    };
  };

  # =========================================================================
  # 5. GLOBAL SERVICE PROVISIONS & ACME MANAGEMENT
  # =========================================================================
  systemd.services.nginx.preStart = ''
    mkdir -p /run/nginx
    echo 'joe:$6$ejalmdDoznQXS6Mh$AATCMicDKyMghwja.SFfMA5bBz80M9qnLW3oWceDiaAuXMgxmlYr4WczgqSLermCqOzOe8jIodUVsKznsmATV.' > /run/nginx/.htpasswd
    chmod 600 /run/nginx/.htpasswd
  '';
  
  security.acme = {
    acceptTerms = true;
    defaults = {
      email = "josephscampo@gmail.com";
      dnsProvider = "porkbun";
      environmentFile = "/etc/porkbun-api.secret";
      dnsResolver = "1.1.1.1:53"; 
      # server = "https://acme-staging-v02.api.letsencrypt.org/directory"; # use to avoid hit limit on prod server

      
      # Use the modern, active lego flags to hard-kill CNAME chasing
      extraLegoFlags = [ 
        "--dns.propagation-disable-ans"
        "--dns.disable-cp" 
      ];
    };
    
    certs."campgroundlabs.xyz" = {
      domain = "campgroundlabs.xyz";
      extraDomainNames = [ "*.campgroundlabs.xyz" ];

    };
  };

  systemd.services."acme-order-renew-campgroundlabs.xyz" = {
    environment = {
      LEGO_DISABLE_CNAME_SUPPORT = "true";
    };
  };

  networking.firewall.allowedTCPPorts = [ 80 443 8443 ];
}